# Proyecto Final — Asistente de regalos
## Calidad de datos
Entendimiento y limpieza del dataset Online Retail II.

### 1. Carga de datos

In [42]:
import pandas as pd

hojas = pd.read_excel('../data/raw/online_retail_II.xlsx', sheet_name=None)  # el Excel trae 2 hojas, una por período
df = pd.concat(hojas.values(), ignore_index=True)  # las uno en una sola tabla
print(df.shape)

(1067371, 8)

**Hallazgo:** el dataset cargó con 1.067.371 filas y 8 columnas,
coincide con lo documentado oficialmente para Online Retail II.

**Diccionario de variables** (para no marearse con los nombres de columna más abajo):

| Columna | Qué es | Notas |
|---|---|---|
| invoice_no | Número de factura/pedido | Si empieza con "C" es cancelación |
| stock_code | Código del producto | Algunos códigos no son productos reales (POST, DOT, M, BANK CHARGES, AMAZONFEE, B) |
| description | Descripción del producto | Texto libre, puede venir vacío |
| quantity | Cantidad comprada en esa línea | Puede ser negativa (cancelaciones o ajustes) |
| invoice_date | Fecha y hora de la transacción | Rango 2009-2011 |
| unit_price | Precio de una unidad | En libras esterlinas (GBP); puede venir en 0 |
| customer_id | Identificador del cliente | Puede venir vacío |
| country | País del cliente | Mayoría Reino Unido |

### 2. Exploración inicial
¿Cuántos datos faltan, qué tipos de dato hay, qué rango de fechas cubre?

In [43]:
df.info()  # tipos de dato de cada columna
display(df.isna().sum())  # cuántos valores faltan por columna

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 78.8+ MB

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

**Hallazgo:** las columnas vinieron como `Invoice`, `Price` y
`Customer ID` (no `InvoiceNo`, `UnitPrice`, `CustomerID`). Hay
243.007 filas sin `Customer ID` (22,8%) y 4.382 sin `Description`
(0,4%) — ambos se van a tratar en la limpieza.

### 3. Normalización de columnas
Las columnas se renombran para trabajar con un estándar fijo (snake_case).

In [44]:
df = df.rename(columns={
    'Invoice': 'invoice_no', 'StockCode': 'stock_code', 'Description': 'description',
    'Quantity': 'quantity', 'InvoiceDate': 'invoice_date', 'Price': 'unit_price',
    'Customer ID': 'customer_id', 'Country': 'country'
})
df.columns.tolist()

['invoice_no',
 'stock_code',
 'description',
 'quantity',
 'invoice_date',
 'unit_price',
 'customer_id',
 'country']

**Hallazgo:** las 8 columnas quedaron normalizadas en snake_case.
A partir de acá, todo el código usa estos nombres.

### 4. Mirando la tabla y sus rangos

In [45]:
display(df.head())  # miro filas reales antes de cualquier estadística

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

**Hallazgo:** la estructura es 1 fila por producto dentro de una
factura (mismo invoice_no se repite). La primera factura (489434)
parecía, mirando solo estas 5 filas, tener todas sus cantidades
en múltiplos de 6 — hay que verificar si head() la cortó.

In [84]:
display(df[df['invoice_no'].astype(str) == '489434'])

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom

**Hallazgo corregido:** la factura 489434 tiene 8 líneas (no 5, como
parecía con head()). De esas, 7 son múltiplo de 6 y 1 no (cantidad 10)
— o sea, 87,5% del patrón bulk, no el 100% que se había dicho antes.
También confirma que códigos con letra al final (79323P, 79323W)
pueden ser productos reales (variantes de color), no solo ajustes
administrativos.

In [85]:
print(df['invoice_no'].apply(type).value_counts())

invoice_no
<class 'int'>    1047871
<class 'str'>      19500
Name: count, dtype: int64

**Hallazgo adicional:** invoice_no también mezcla tipos de dato en 
el Excel crudo — 1.047.871 filas como entero, 19.500 como texto 
(las que empiezan con "C", que la letra obliga a ser string). Mismo 
patrón que stock_code. Confirma que normalizar_tipos() es necesario 
para TODAS las columnas de identificador, no solo stock_code.

### 5. Rangos y valores extremos

In [47]:
display(df.describe())  # count, media, min, max, cuartiles de las columnas numéricas

           quantity                invoice_date    unit_price    customer_id
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

**Hallazgo:** quantity tiene un rango de -80.995 a +80.995, mientras
que unit_price llega a -53.594,36. Son valores extremos poco
habituales — hay que investigarlos antes de decidir cómo tratarlos.

### 6. Casos sospechosos: cantidad o precio no válidos

In [48]:
display(df[(df['quantity'] <= 0) | (df['unit_price'] <= 0)].head(10))  # miro una muestra
print('cantidad <= 0:', (df['quantity'] <= 0).sum())
print('unit_price <= 0:', (df['unit_price'] <= 0).sum())

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

cantidad <= 0: 22950
unit_price <= 0: 6207

**Hallazgo:** 22.950 filas tienen quantity <= 0, más que las 19.494
cancelaciones formales (invoice_no con "C") — hay ~3.456 filas con
cantidad negativa o cero que no están marcadas como cancelación
oficial (se investiga en la sección 9). El filtro quantity > 0 las
saca a todas de todos modos. Aparte, 6.207 filas tienen
unit_price <= 0 (incluye los 4 casos de "Adjust bad debt" de la
sección 7, más ceros).

### 6.1 Duplicados exactos

In [49]:
print(df.duplicated().sum(), "filas duplicadas exactas")  # cuenta filas idénticas en TODAS sus columnas

34335 filas duplicadas exactas

In [50]:
display(df[df.duplicated(keep=False)].sort_values(['invoice_no', 'stock_code']).head(10))  # ejemplo real, no solo el número

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom

**Hallazgo:** 34.335 filas duplicadas exactas (3,2% del dataset).
Un ejemplo real: "VINTAGE SNAKES & LADDERS" aparece 3 veces en la
misma factura, cada una con quantity=1 — no se ve como 1 compra
de 3 unidades en una sola línea, sino como 3 líneas separadas.

### 6.2 ¿Se repite el patrón en los 34.335?

In [51]:
duplicados = df[df.duplicated(keep=False)]
print(duplicados['quantity'].value_counts().head())  # ¿la mayoría tiene quantity=1, como en el ejemplo?

repeticiones = duplicados.groupby(['invoice_no', 'stock_code']).size()  # cuántas veces se repite cada combinación factura+producto
print(repeticiones.describe())

quantity
1     31263
2      9661
12     4896
6      4300
3      3776
Name: count, dtype: int64
count    32597.000000
mean         2.062828
std          0.377345
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max         20.000000
dtype: float64

**Hallazgo:** el 75% de las combinaciones factura+producto
duplicadas se repite exactamente 2 veces (mediana = 2). Si
descartáramos duplicados quedándonos con 1 sola fila, perderíamos
la cantidad real que se llevó el cliente (ej. quedaría quantity=1
en vez de 3).

**Decisión:** no se usa drop_duplicates() a secas. Se agrupan las
filas duplicadas y se suma quantity, para conservar la cantidad
real que se llevó el cliente en vez de perderla al quedarse con
una sola fila.

### 7. Investigando el precio negativo extremo

In [52]:
display(df[df['unit_price'] < 0][['stock_code', 'description', 'unit_price']].drop_duplicates())  # ¿qué productos tienen precio negativo?

       stock_code      description  unit_price
179403          B  Adjust bad debt   -53594.36
276274          B  Adjust bad debt   -44031.79
403472          B  Adjust bad debt   -38925.87
825444          B  Adjust bad debt   -11062.06

**Hallazgo:** stock_code "B" = "Adjust bad debt" — es un ajuste
contable por deuda incobrable, no una venta real. Se suma a la
lista de códigos no-producto a sacar en la limpieza (junto con
POST, DOT, M, BANK CHARGES, AMAZONFEE).

### 7.1 Auditoría de códigos que no siguen el patrón estándar

In [53]:
codigos_raros = df[~df['stock_code'].astype(str).str.match(r'^\d{5}$')]['stock_code'].unique()  # códigos que NO son 5 dígitos seguidos (astype(str): stock_code mezcla int y str en el Excel crudo)
print(len(codigos_raros), "códigos distintos no son 5 dígitos seguidos")
print(sorted(codigos_raros)[:30])  # primeros 30, para no inundar la pantalla

1715 códigos distintos no son 5 dígitos seguidos
['10002R', '10123C', '10123G', '10124A', '10124C', '10124G', '15044A', '15044B', '15044C', '15044D', '15056BL', '15056N', '15056P', '15056bl', '15056n', '15056p', '15058A', '15058B', '15058C', '15059A', '15060A', '15060B', '15060b', '16020C', '16065A', '16151A', '16155H', '16156A', '16156L', '16156N']

**Hallazgo:** 1.715 códigos no siguen el patrón de 5 dígitos. La
mayoría son variantes de color/tamaño de un producto base (ej.
10124A, 10124C, 10124G) — productos reales, no administrativos.

In [54]:
tipos = df['stock_code'].apply(type).value_counts()  # confirmo por qué hizo falta el astype(str) de arriba
print(tipos)

stock_code
<class 'int'>    932385
<class 'str'>    134986
Name: count, dtype: int64

**Hallazgo:** stock_code en el Excel crudo mezcla tipos de dato —
932.385 filas como número entero, 134.986 como texto. Excel guarda
así las celdas puramente numéricas (ej. 20725) distinto de las
alfanuméricas (ej. 85123A). Esto confirma por qué normalizar_tipos()
fuerza todo a texto antes de cualquier otra operación — no es solo
prolijidad, es necesario para que el código no se rompa.

### 7.2 ¿Son duplicados por mayúscula/minúscula?

In [55]:
print(df['stock_code'].nunique(), "códigos distintos (mayúscula y minúscula por separado)")  # cuenta cada variante de caso como distinta
print(df['stock_code'].astype(str).str.upper().nunique(), "códigos distintos después de unificar mayúsculas")  # unifico y cuento de nuevo

5305 códigos distintos (mayúscula y minúscula por separado)
5132 códigos distintos después de unificar mayúsculas

**Hallazgo:** 5.305 códigos distintos bajan a 5.132 al unificar
mayúsculas — 173 eran el mismo producto escrito distinto (ej.
15056BL y 15056bl). Confirma que normalizar con .str.upper() en
la limpieza es necesario, no una precaución de más.

### 7.3 Acotar los candidatos reales a revisar

In [56]:
precio_cero_siempre = df.groupby('stock_code')['unit_price'].apply(lambda s: (s == 0).all())  # True si TODAS las ventas de ese código tienen precio 0
sospechosos = precio_cero_siempre[precio_cero_siempre].index.tolist()  # me quedo solo con los códigos marcados True
print(len(sospechosos), "códigos con TODAS sus filas en precio 0 (candidatos reales a revisar)")

373 códigos con TODAS sus filas en precio 0 (candidatos reales a revisar)

**Hallazgo:** 373 códigos tienen precio 0 en el 100% de sus ventas.
La mayoría son productos reales de 5 dígitos (muestras o
promociones) — el filtro unit_price > 0 ya los saca a todos sin
necesitar código nuevo.

### 7.4 Revisar los más raros entre los sospechosos

In [57]:
sospechosos_especiales = ['C3', 'GIFT', 'gift_0001_60', 'gift_0001_90', 'DCGS0006', 'DCGS0016', 'DCGS0027',
                           'DCGS0036', 'DCGS0039', 'DCGS0053', 'DCGS0055', 'DCGS0056', 'DCGS0057', 'DCGS0059',
                           'DCGS0060', 'DCGS0066P', 'DCGS0067', 'DCGS0071', 'DCGS0073', 'DCGS0074',
                           'DCGSLBOY', 'DCGSLGIRL']
display(df[df['stock_code'].isin(sospechosos_especiales)][['stock_code', 'description']].drop_duplicates())  # miro sus descripciones reales

          stock_code description
75138   gift_0001_60         NaN
75141   gift_0001_90         NaN
80337       DCGS0006         NaN
80338       DCGS0016         NaN
80339       DCGS0027         NaN
80342       DCGS0036         NaN
80361       DCGS0039         NaN
80953       DCGS0060         NaN
81143       DCGS0056         NaN
82846       DCGS0059         NaN
83304           GIFT         NaN
89000       DCGSLBOY         NaN
98950       DCGS0053         NaN
101693     DCGSLGIRL         NaN
302041            C3         NaN
600298      DCGS0055         NaN
600300      DCGS0074         NaN
600756      DCGS0057         NaN
804712      DCGS0073        ebay
804713      DCGS0071         NaN
804715     DCGS0066P         NaN
804718      DCGS0067        ebay

**Hallazgo:** de los 373 códigos con precio siempre en 0, 22 (los
"gift_", "GIFT", "DCGS0XXX", "C3") tienen descripción vacía o solo
"ebay" — sin evidencia de ser productos identificables.

**Decisión:** no se agregan a la lista de códigos no-producto.
catalogo_productos() ya descarta cualquier stock_code sin
descripción, así que estos 22 nunca llegan a mostrarse ni a
recomendarse en el asistente.

### 8. País y cancelaciones

In [58]:
display(df['country'].value_counts().head(10))  # top 10 países
print(df['invoice_no'].astype(str).str.startswith('C').sum(), "filas de cancelación")  # cuántas son devoluciones

country
United Kingdom    981330
EIRE               17866
Germany            17624
France             14330
Netherlands         5140
Spain               3811
Switzerland         3189
Belgium             3123
Portugal            2620
Australia           1913
Name: count, dtype: int64

19494 filas de cancelación

**Hallazgo:** United Kingdom es el 91,9% de las filas (981.330 de
1.067.371). Hay 19.494 filas de cancelación (1,8%).

### 9. Cantidad negativa SIN ser cancelación formal

In [59]:
mask = (df['quantity'] < 0) & (~df['invoice_no'].astype(str).str.startswith('C'))  # cantidad negativa Y NO es cancelación formal
print(mask.sum(), "filas con cantidad negativa que no son cancelación 'C'")
display(df[mask].head(10))  # miro una muestra para tener una primera idea

3457 filas con cantidad negativa que no son cancelación 'C'

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0,NaN,United Kingdom
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom

In [60]:
print('todas con unit_price == 0:', (df[mask]['unit_price'] == 0).all())  # ¿se cumple en TODAS, o solo en la muestra que vi?
print('todas con customer_id nulo:', df[mask]['customer_id'].isna().all())

todas con unit_price == 0: True
todas con customer_id nulo: True

**Hallazgo:** las 3.457 filas con cantidad negativa que no son
cancelación formal tienen el 100% unit_price = 0 y 100%
customer_id nulo — confirmado sobre las 3.457 filas completas, no
solo sobre una muestra. Son ajustes de inventario escritos a
mano ("lost", "damages", "short", "invcd as..."), no ventas ni
cancelaciones de cliente. El filtro unit_price > 0 (ya planeado)
las saca a todas — no hace falta un filtro nuevo para esto.

### 9.1 Reconciliando la diferencia de 1 fila (3.456 vs 3.457)

In [61]:
mask_rara = df['invoice_no'].astype(str).str.startswith('C') & (df['quantity'] >= 0)  # facturas "C" con cantidad NO negativa
print(mask_rara.sum(), "facturas 'C' con cantidad >= 0")
display(df[mask_rara])  # veo de qué se trata

1 facturas 'C' con cantidad >= 0

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,NaN,United Kingdom

**Hallazgo:** la diferencia de 1 fila (3.457 vs 3.456) era una
factura "C" con stock_code "M" (Manual) y cantidad positiva — un
ajuste administrativo cargado con prefijo de cancelación, no una
cancelación real de cliente.

**Decisión:** no hace falta ningún cambio en el código de limpieza
— esta fila ya se excluye sola con el filtro de códigos no-producto
existente (stock_code "M" está en CODIGOS_NO_PRODUCTO).

### 10. ¿El patrón de la primera factura se repite en todo el dataset?

In [62]:
proporcion_multiplo = (df['quantity'] % 6 == 0).groupby(df['invoice_no']).mean()  # % de líneas múltiplo de 6, por factura
display(proporcion_multiplo.describe())

n_productos = df.groupby('invoice_no')['stock_code'].nunique()  # productos distintos por factura
es_bulk = (proporcion_multiplo >= 0.8) & (n_productos >= 5)  # 80%+ en múltiplos de 6 Y al menos 5 productos
print(f"% facturas bulk (proporción 80% + mínimo 5 productos): {es_bulk.mean():.1%}")

count    53628.000000
mean         0.352582
std          0.353950
min          0.000000
25%          0.000000
50%          0.250000
75%          0.647059
max          1.000000
Name: quantity, dtype: float64

% facturas bulk (proporción 80% + mínimo 5 productos): 7.1%

**Hallazgo:** la proporción de líneas en múltiplos de 6 por factura
tiene mediana 0,25 y percentil 75 de 0,647 — la mayoría de las
facturas no se acerca al patrón bulk. Con el criterio corregido
(80%+ de las líneas en múltiplos de 6, Y al menos 5 productos
distintos), el 7,1% de las facturas califica como bulk. Una sola
excepción en una factura de 1.110 productos no debería descartarla
— por eso se usa proporción, no el 100% exacto que se había
considerado al principio.

### 11. Impacto de conservar filas sin customer_id

In [63]:
con_cliente = df.dropna(subset=['customer_id'])  # como quedaría si exigimos cliente

print(f"Facturas totales: {df['invoice_no'].nunique()} | con cliente: {con_cliente['invoice_no'].nunique()}")
print(f"Productos distintos totales: {df['stock_code'].nunique()} | con cliente: {con_cliente['stock_code'].nunique()}")

Facturas totales: 53628 | con cliente: 44876
Productos distintos totales: 5305 | con cliente: 4646

**Hallazgo:** exigir customer_id elimina 8.752 facturas completas
(16,3%) y 659 productos distintos (12,4% del catálogo) que solo
aparecen en compras sin cliente registrado.

**Decisión:** se arman 2 datasets a partir de acá. Para RFM y
segmentación mayorista/minorista: pipeline_completo(conservar_sin_cliente=False)
— ahí SÍ hace falta saber quién compró. Para el modelo de
recomendación (matriz factura-producto):
pipeline_completo(conservar_sin_cliente=True) — el modelo no
pregunta quién compró, y descartar esas filas le esconde 1 de
cada 8 productos del catálogo.

## Conclusión: qué aprendimos antes de limpiar

El dataset tiene 1.067.371 filas y 8 columnas, consistente con lo
documentado oficialmente. Las columnas no venían estandarizadas,
así que las normalizamos a snake_case.

**Valores extremos investigados — 2 hipótesis razonables, no
confirmadas con certeza:**
1. Stock_code "B" trae la descripción "Adjust bad debt". Nuestra
   interpretación: es un ajuste contable por deuda incobrable, no
   una venta — apoyada en que el precio es negativo y enorme, pero
   no hay forma de confirmarlo con quien armó el dataset.
2. 3.457 filas con cantidad negativa, sin ser cancelación formal,
   traen descripciones como "lost", "damages", "short", con 100%
   precio=0 y 100% sin cliente. Nuestra lectura: pérdida o daño de
   inventario, no una compra — razonable dado el patrón, pero
   también una interpretación, no un hecho verificado.

Reino Unido concentra el 91,9% de las filas (hecho medido);
cancelaciones formales son el 1,8% (hecho medido).

**Códigos de producto:** 1.715 no siguen el patrón de 5 dígitos
(hecho medido). Revisando sus descripciones, la mayoría parecen
variantes de color o tamaño de un mismo producto (confirmado
viendo el texto real, ej. 79323P/79323W = "PINK/WHITE CHERRY
LIGHTS"). Unificar mayúsculas bajó los códigos distintos de 5.305
a 5.132 (hecho medido). De 373 códigos con precio siempre en 0,
22 no tienen descripción real — ya quedan afuera del catálogo
automáticamente.

**Duplicados exactos:** 34.335 filas (3,2%, hecho medido). Se
agrupa y suma `quantity` en vez de descartar, para no perder
cantidad real comprada.

**Patrón de "facturas bulk":** le llamamos así a una hipótesis de
reposición al por mayor, inferida de que las cantidades vienen en
múltiplos de 6 y hay varios productos distintos — no es un dato
confirmado, es un patrón que medimos (7,1% de las facturas, con
80%+ de líneas en múltiplos de 6 y mínimo 5 productos).

**Clientes sin identificar:** exigir customer_id perdería 8.752
facturas (16,3%) y 659 productos (12,4% del catálogo) — esto sí es
un hecho medido directo. Por eso se generan 2 datasets: uno exige
cliente (RFM), otro lo conserva (modelo de recomendación).

Con esto, la limpieza queda justificada con evidencia propia —
distinguiendo qué se midió directamente y qué es una interpretación
razonable de esa evidencia, no un hecho confirmado al 100%.

### 12. Aplicando la limpieza real
Corremos el pipeline de limpieza (src/data/clean.py) para generar los datasets finales.

In [64]:
import sys
sys.path.append('..')

from src.data import clean
import importlib
importlib.reload(clean)  # por si el módulo ya estaba cargado en memoria con una versión vieja
from src.data.clean import pipeline_completo

**Hallazgo:** la primera corrida del pipeline mostró 3 pasos
consecutivos con el mismo número de filas ("sin duplicados", "sin
descripción vacía", "con customer_id") — señal de que groupby()
estaba descartando de más. Por default, pandas tira las filas con
NaN en las columnas de agrupamiento, y en ese punto del pipeline
customer_id y description todavía tenían NaN.

**Decisión:** se agregó dropna=False al groupby() de limpiar_datos()
en clean.py, para que agrupe los NaN entre sí en vez de descartarlos.
Con el fix, cada filtro saca solo lo que le corresponde. También se
encontró que pipeline_completo() no le pasaba conservar_sin_cliente
a limpiar_datos() — corregido.

In [65]:
df_rfm, log_rfm = pipeline_completo('../data/raw/online_retail_II.xlsx', 
                                     '../data/processed/online_retail_rfm.parquet')
display(log_rfm)

                               paso   filas  facturas
                            inicial 1044848     53628
 sin compras con cancelación exacta 1043348     53404
                  sin cancelaciones 1024183     45112
              cantidad y precio > 0 1018154     39849
            sin códigos no-producto 1013721     39398
sin duplicados (cantidades sumadas)  991564     39398
              sin descripción vacía  991564     39398
                    con customer_id  764956     36490

                                  paso    filas  facturas
0                              inicial  1044848     53628
1   sin compras con cancelación exacta  1043348     53404
2                    sin cancelaciones  1024183     45112
3                cantidad y precio > 0  1018154     39849
4              sin códigos no-producto  1013721     39398
5  sin duplicados (cantidades sumadas)   991564     39398
6                sin descripción vacía   991564     39398
7                      con customer_id   764956     36490

**Hallazgo:** dataset para RFM: 766.521 filas, 36.650 facturas.
Se pierden 2.930 facturas al exigir customer_id (7,4% de las
39.580 que quedaban en ese punto del pipeline).

In [71]:
df_modelo, log_modelo = pipeline_completo('../data/raw/online_retail_II.xlsx',
                                            '../data/processed/online_retail_modelo.parquet',
                                            conservar_sin_cliente=True)
display(log_modelo)

                               paso   filas  facturas
                            inicial 1044848     53628
 sin compras con cancelación exacta 1043348     53404
                  sin cancelaciones 1024183     45112
              cantidad y precio > 0 1018154     39849
            sin códigos no-producto 1013721     39398
sin duplicados (cantidades sumadas)  991564     39398
              sin descripción vacía  991564     39398

                                  paso    filas  facturas
0                              inicial  1044848     53628
1   sin compras con cancelación exacta  1043348     53404
2                    sin cancelaciones  1024183     45112
3                cantidad y precio > 0  1018154     39849
4              sin códigos no-producto  1013721     39398
5  sin duplicados (cantidades sumadas)   991564     39398
6                sin descripción vacía   991564     39398

**Hallazgo:** el dataset del modelo (conservar_sin_cliente=True)
tiene 993.249 filas y 39.580 facturas — 2.930 facturas más que el
de RFM (766.521 filas, 36.650 facturas), confirmando que se
recuperan las ventas sin cliente identificado para el modelo de
recomendación, sin afectar el dataset usado para RFM.

### 13. Revisión del PR
La revisión del PR de calidad-datos encontró varios puntos
reales. Ya se corrigieron en clean.py: solapamiento entre hojas del
Excel (1.088 facturas de diciembre 2010 duplicadas), el bloque
`__main__` que generaba un solo archivo en vez de los 2
documentados, y faltaba `openpyxl` en requirements.txt. Lo que
sigue acá es lo que necesitaba verificación con datos antes de
decidir el fix.

### 13.1 Códigos raros que sobrevivieron a la limpieza

In [72]:
codigos_raros_sobrevivientes = df_modelo[~df_modelo['stock_code'].str.match(r'^\d{5}$')]['stock_code'].unique()  # mismo chequeo de la 7.1, ahora sobre el dataset YA limpio
print(len(codigos_raros_sobrevivientes))
print(sorted(codigos_raros_sobrevivientes))

1343
['10002R', '10123C', '10123G', '10124A', '10124G', '15044A', '15044B', '15044C', '15044D', '15056BL', '15056N', '15056P', '15058A', '15058B', '15058C', '15059A', '15060B', '16020C', '16151A', '16156L', '16156N', '16156S', '16161C', '16161E', '16161G', '16161M', '16161P', '16161U', '16162L', '16162M', '16168M', '16168S', '16169A', '16169C', '16169D', '16169E', '16169F', '16169G', '16169K', '16169M', '16169N', '16169P', '16201A', '16201B', '16202A', '16202B', '16202C', '16202E', '16206B', '16207A', '16207B', '16243B', '16244A', '16244B', '16245A', '16248B', '16256B', '16256C', '16258A', '16258B', '17007B', '17011A', '17011B', '17011C', '17011D', '17011E', '17011F', '17012A', '17012B', '17012C', '17012D', '17012E', '17012F', '17013B', '17013C', '17013D', '17013F', '17014A', '17014C', '17014D', '17014E', '17014F', '17027A', '17028J', '17084A', '17084G', '17084J', '17084N', '17084P', '17084R', '17090A', '17090D', '17091A', '17091B', '17091F', '17091J', '17107D', '17108D', '17109A', '17109B', '17109C', '17109D', '17129C', '17129D', '17129F', '17136A', '17164B', '17164D', '17165B', '17165D', '17191A', '18094C', '18096C', '18097A', '18097B', '18097C', '18098A', '18098B', '18098C', '30086C', '35001B', '35001G', '35001P', '35001W', '35004B', '35004C', '35004G', '35004P', '35004S', '35051B', '35085E', '35095A', '35095B', '35096A', '35096B', '35271S', '35471A', '35471D', '35591T', '35597A', '35597B', '35597D', '35598A', '35598B', '35598C', '35598D', '35599B', '35599D', '35600D', '35603B', '35603C', '35607A', '35607B', '35609A', '35610A', '35610B', '35610C', '35611B', '35633B', '35637A', '35637C', '35638A', '35638B', '35751C', '35751D', '35809A', '35809B', '35810A', '35810B', '35811A', '35815B', '35815P', '35816B', '35816P', '35817B', '35817P', '35818B', '35818C', '35818P', '35819B', '35819P', '35821B', '35821P', '35822B', '35822P', '35823P', '35824B', '35824C', '35824P', '35833G', '35833P', '35838A', '35838B', '35909A', '35909B', '35910A', '35910B', '35911A', '35911B', '35912B', '35913B', '35915A', '35915B', '35915C', '35916A', '35916B', '35916C', '35918B', '35976B', '35980B', '35980C', '35981C', '37379A', '37379B', '37444A', '37444B', '37444C', '37462B', '37462E', '37477B', '37477C', '37479B', '37479P', '37482B', '37482P', '37487B', '37488A', '37489A', '37489B', '37489C', '37489D', '37491A', '37491B', '37491C', '37491D', '37492A', '37492B', '37492C', '37492D', '37494A', '40005B', '40018E', '40018F', '40046A', '40046C', '44089A', '44089C', '44091A', '44091C', '44092B', '44092C', '44217M', '44241C', '44242A', '44242B', '45008C', '46000M', '46000P', '46000R', '46000S', '46000U', '46037A', '46115B', '46126A', '46137D', '46138B', '46138D', '46775A', '46775B', '46775D', '46775E', '46776A', '46776B', '46776C', '46776D', '46776E', '46776F', '47013A', '47013C', '47021G', '47310M', '47341A', '47341B', '47343A', '47344B', '47347B', '47348A', '47351B', '47367B', '47369A', '47369B', '47503A', '47503E', '47503F', '47503G', '47503H', '47503J', '47503K', '47504E', '47504F', '47504G', '47504H', '47504J', '47504K', '47518F', '47552A', '47556B', '47559B', '47563A', '47563B', '47566B', '47567B', '47570B', '47574A', '47574B', '47578A', '47581B', '47583A', '47583B', '47585A', '47586A', '47587A', '47590A', '47590B', '47591A', '47591B', '47591C', '47591D', '47592A', '47592B', '47593A', '47593B', '47594A', '47594B', '47599A', '47599B', '48173A', '48173C', '51012C', '51012L', '51014A', '51014C', '51014L', '51020A', '51020B', '62043B', '62074B', '62086A', '62094B', '62095B', '62096A', '62096B', '62097A', '62097B', '71028B', '71101A', '71101E', '71406C', '71434B', '71495A', '71495B', '71496A', '71496B', '72023F', '72024U', '72038P', '72045D', '72051S', '72083A', '72084B', '72140E', '72140F', '72225C', '72225D', '72349B', '72351A', '72351B', '72369A', '72529W', '72606A', '72739B', '72739C', '72740A', '72740B', '72750A', '72750B', '72750C', '72750D', '72751A', '72751B', '72751C', '72752A', '72752B', '72753A', '72753B', '72753C', '72753D', '72754A', '72754B', '72754D', '72755C', '72755D', '72760B', '72771B', '72771C', '72785A', '72785B', '72796A', '72796B', '72796C', '72798C', '72799A', '72799B', '72799C', '72799D', '72799E', '72799F', '72800A', '72800B', '72800C', '72800D', '72800E', '72800F', '72801C', '72801D', '72801E', '72801F', '72801G', '72802A', '72802B', '72802C', '72803A', '72803B', '72807A', '72807B', '72807C', '75013B', '75049L', '75149N', '77101A', '78034B', '79026B', '79030A', '79030D', '79030G', '79051A', '79062D', '79063C', '79063D', '79065A', '79066K', '79070B', '79071B', '79144B', '79144C', '79149B', '79151B', '79157B', '79157V', '79161A', '79172D', '79190A', '79190B', '79190D', '79191B', '79191C', '79191D', '79192A', '79302M', '79303A', '79303B', '79303D', '79308B', '79315W', '79323B', '79323G', '79323GR', '79323LP', '79323P', '79323S', '79323W', '79342B', '81950B', '81950V', '81952B', '81952V', '81953B', '81953P', '81985A', '82001S', '82011A', '82011B', '82011C', '82011E', '82494L', '82545A', '82607A', '82607C', '82607E', '82613A', '82613B', '82613C', '82613D', '82616A', '82616B', '82616C', '84029C', '84029D', '84029E', '84029G', '84030B', '84030C', '84030E', '84031A', '84031B', '84032A', '84032B', '84078A', '84086B', '84086C', '84201B', '84201C', '84205C', '84206A', '84206B', '84206C', '84247C', '84247E', '84247G', '84247H', '84247J', '84247K', '84247L', '84247N', '84249A', '84249D', '84250M', '84251B', '84251C', '84251F', '84251G', '84251J', '84255A', '84255B', '84279B', '84279P', '84288B', '84292B', '84313A', '84313B', '84313C', '84327A', '84341B', '84387A', '84402B', '84402D', '84405A', '84406B', '84414B', '84415A', '84415B', '84424A', '84425A', '84427B', '84429A', '84437A', '84450A', '84450B', '84459A', '84459B', '84507B', '84507C', '84508A', '84508B', '84508C', '84509A', '84509B', '84509C', '84509E', '84509F', '84509G', '84510A', '84510B', '84510C', '84510E', '84510F', '84519A', '84519B', '84520B', '84520D', '84529A', '84529B', '84529C', '84531A', '84531B', '84532B', '84533B', '84534B', '84535A', '84535B', '84536A', '84536B', '84537B', '84555A', '84558A', '84559A', '84559B', '84559D', '84562A', '84562B', '84563A', '84563B', '84569A', '84569B', '84569C', '84569D', '84570B', '84575A', '84575B', '84586L', '84595B', '84595E', '84596B', '84596E', '84596F', '84596G', '84596I', '84596J', '84596K', '84596L', '84597B', '84597C', '84601A', '84611B', '84612B', '84613A', '84613C', '84614A', '84614C', '84625A', '84625B', '84625C', '84625D', '84659A', '84660A', '84660B', '84660C', '84661A', '84661B', '84661C', '84663A', '84671B', '84673A', '84673B', '84705A', '84705B', '84705C', '84705D', '84705F', '84706A', '84706B', '84706C', '84706D', '84706F', '84707A', '84707B', '84708B', '84709A', '84709B', '84711A', '84711B', '84712B', '84732B', '84732D', '84741C', '84743C', '84745A', '84745B', '84750A', '84750B', '84751B', '84753A', '84760L', '84760S', '84762A', '84762B', '84762C', '84782A', '84782B', '84782C', '84795A', '84795B', '84795C', '84795D', '84795E', '84796A', '84796B', '84797A', '84797B', '84798A', '84798B', '84798C', '84800L', '84800M', '84800S', '84801A', '84801B', '84802A', '84802B', '84803A', '84803B', '84804A', '84804B', '84805A', '84805B', '84806A', '84806B', '84809A', '84809B', '84814A', '84814B', '84845A', '84845C', '84845D', '84846A', '84849A', '84849B', '84849D', '84856L', '84856S', '84857A', '84857B', '84857C', '84858A', '84858B', '84858C', '84859A', '84859B', '84859C', '84864A', '84867A', '84867B', '84868A', '84868B', '84870B', '84870C', '84872A', '84873A', '84874B', '84875A', '84875B', '84875D', '84876B', '84876C', '84876D', '84877A', '84877B', '84877D', '84884A', '84891B', '84898F', '84899E', '84899F', '84908A', '84908B', '84909A', '84910A', '84912A', '84912B', '84913A', '84913B', '84914A', '84924A', '84924D', '84924F', '84925A', '84925C', '84925D', '84925E', '84925F', '84926A', '84926B', '84926C', '84926D', '84926E', '84926F', '84927A', '84927D', '84927E', '84927F', '84931A', '84931B', '84932A', '84932B', '84932C', '84932D', '84933A', '84933B', '84933C', '84951A', '84951B', '84952A', '84952B', '84952C', '84963A', '84963B', '84964A', '84964B', '84965A', '84965B', '84966A', '84966B', '84966C', '84967A', '84967B', '84967C', '84968A', '84968B', '84968C', '84968D', '84968E', '84968F', '84970L', '84970S', '84971L', '84971S', '84972L', '84984A', '84984B', '84984C', '84984D', '84985A', '84985B', '84986B', '84989A', '84989B', '84993A', '84993B', '84997A', '84997B', '84997C', '84997D', '85014A', '85014B', '85014C', '85014D', '85017A', '85017B', '85017C', '85018A', '85018B', '85018C', '85018D', '85019A', '85019B', '85019C', '85023A', '85023B', '85023C', '85024A', '85024B', '85024C', '85025B', '85025C', '85026B', '85027L', '85028L', '85028S', '85031A', '85031B', '85031C', '85032A', '85032B', '85032C', '85032D', '85033G', '85033S', '85034A', '85034B', '85034C', '85035A', '85035B', '85035C', '85036A', '85036B', '85036C', '85039A', '85039B', '85039C', '85040A', '85040B', '85049A', '85049B', '85049C', '85049D', '85049E', '85049F', '85049G', '85049H', '85061W', '85071A', '85071B', '85071C', '85071D', '85086A', '85097B', '85098B', '85099B', '85099C', '85099F', '85114A', '85114B', '85114C', '85115B', '85121B', '85121C', '85123A', '85123B', '85124A', '85124B', '85124C', '85129A', '85129B', '85129C', '85129D', '85130A', '85130B', '85130C', '85130D', '85131A', '85131B', '85131C', '85131D', '85132A', '85132B', '85132C', '85135A', '85135B', '85135C', '85136A', '85136B', '85136C', '85159A', '85159B', '85160A', '85160B', '85162A', '85162B', '85162C', '85163A', '85163B', '85164B', '85166A', '85166B', '85167A', '85167B', '85168A', '85168B', '85169A', '85169B', '85169C', '85169D', '85170A', '85170B', '85170C', '85170D', '85179A', '85179B', '85179C', '85180A', '85180B', '85183A', '85183B', '85184B', '85184C', '85184D', '85185B', '85185C', '85185D', '85185E', '85185F', '85186A', '85186B', '85186C', '85188A', '85188B', '85192S', '85194L', '85194S', '85199L', '85199S', '85205A', '85205B', '85206A', '85206B', '85226A', '85226C', '85230A', '85230B', '85230C', '85230D', '85230E', '85230F', '85230G', '85231B', '85231E', '85231G', '85231L', '85232A', '85232B', '85232C', '85232D', '90000A', '90000B', '90000C', '90000D', '90001A', '90001B', '90001C', '90001D', '90002A', '90002B', '90002C', '90002D', '90002E', '90003B', '90003C', '90003D', '90003E', '90004A', '90005A', '90010A', '90010B', '90010E', '90011A', '90011B', '90011C', '90011D', '90011E', '90012A', '90012B', '90013A', '90013B', '90013C', '90013D', '90013E', '90014A', '90014B', '90014C', '90016A', '90016B', '90016C', '90018A', '90018B', '90018C', '90019A', '90019B', '90019C', '90024A', '90024B', '90024C', '90024D', '90024E', '90024F', '90025A', '90025B', '90025C', '90025D', '90025E', '90025F', '90026A', '90026B', '90026C', '90026D', '90027A', '90027B', '90027C', '90027D', '90030A', '90030B', '90030C', '90035A', '90035B', '90035C', '90036A', '90036B', '90036C', '90036D', '90036E', '90036F', '90037A', '90037B', '90037C', '90037D', '90038A', '90038B', '90038C', '90039A', '90039B', '90039C', '90039D', '90040A', '90040B', '90040C', '90040D', '90042A', '90042B', '90042C', '90058A', '90058B', '90059A', '90059B', '90059C', '90059D', '90059E', '90059F', '90060B', '90060C', '90060D', '90060F', '90063A', '90063B', '90064A', '90064B', '90065A', '90065B', '90066A', '90067A', '90067B', '90081A', '90081B', '90081C', '90082A', '90082B', '90082C', '90082D', '90120A', '90120B', '90120C', '90120D', '90121B', '90122A', '90122B', '90122C', '90123A', '90123B', '90123C', '90123D', '90124A', '90124B', '90124C', '90125A', '90125B', '90125C', '90125D', '90125E', '90126A', '90126B', '90126C', '90127A', '90127B', '90128A', '90128B', '90128C', '90128D', '90129A', '90129B', '90129C', '90129D', '90129E', '90129F', '90130A', '90130B', '90130C', '90130D', '90135A', '90141A', '90141B', '90141C', '90141D', '90141E', '90142A', '90142B', '90142C', '90142D', '90152A', '90152B', '90152C', '90160A', '90160B', '90160C', '90160D', '90161A', '90161B', '90161C', '90161D', '90162A', '90162B', '90162C', '90162D', '90163A', '90163B', '90164A', '90164B', '90165A', '90165B', '90175A', '90175B', '90175C', '90175D', '90176A', '90176B', '90176C', '90176D', '90176E', '90177A', '90177B', '90177C', '90177D', '90177E', '90178A', '90178B', '90179A', '90179B', '90179C', '90180A', '90180B', '90181A', '90181B', '90181C', '90182A', '90182B', '90182C', '90183A', '90183B', '90183C', '90184A', '90184B', '90184C', '90185A', '90185B', '90185C', '90185D', '90186A', '90186B', '90187A', '90187B', '90189A', '90189B', '90190A', '90190B', '90190C', '90195A', '90195B', '90196A', '90196B', '90197B', '90197D', '90198A', '90198B', '90199A', '90199B', '90199C', '90199D', '90200A', '90200B', '90200C', '90200D', '90200E', '90201A', '90201B', '90201C', '90201D', '90202A', '90202B', '90202C', '90202D', '90205A', '90205C', '90206A', '90206C', '90209A', '90209B', '90209C', '90210A', '90210B', '90210C', '90210D', '90211A', '90211B', '90212B', '90212C', '90214A', '90214B', '90214C', '90214D', '90214E', '90214F', '90214G', '90214H', '90214I', '90214J', '90214K', '90214L', '90214M', '90214N', '90214O', '90214P', '90214R', '90214S', '90214T', '90214U', '90214V', '90214W', '90214Y', '90214Z', 'DCGS0003', 'DCGS0004', 'DCGS0037', 'DCGS0041', 'DCGS0044', 'DCGS0058', 'DCGS0062', 'DCGS0066N', 'DCGS0068', 'DCGS0069', 'DCGS0070', 'DCGS0072', 'DCGS0075', 'DCGS0076', 'DCGSSBOY', 'DCGSSGIRL', 'GIFT_0001_10', 'GIFT_0001_20', 'GIFT_0001_30', 'GIFT_0001_40', 'GIFT_0001_50', 'GIFT_0001_70', 'GIFT_0001_80', 'PADS', 'SP1002', 'TEST001', 'TEST002']

**Hallazgo:** 1.343 códigos no son 5 dígitos — la gran mayoría son
variantes reales de color/tamaño, mismo patrón que ya veníamos
confirmando (ej. 79323B, 79323G, 79323GR, 79323LP). Dos saltan
como candidatos reales a código administrativo: **TEST001** y
**TEST002** — el nombre sugiere entradas de prueba del sistema.
De paso, se corrige algo mal asumido antes: los códigos DCGS*
(DCGS0066N, DCGS0068, etc.) sí tienen descripciones de producto
real ("CAMOUFLAGE DOG COLLAR") — DCGS no es un prefijo
administrativo en general, la sospecha inicial era de una muestra
chica.

### 13.2 Verificando los candidatos a código administrativo

In [73]:
candidatos = ['TEST001', 'TEST002', 'DCGSSBOY', 'DCGSSGIRL']
display(df_modelo[df_modelo['stock_code'].isin(candidatos)][['stock_code', 'description', 'unit_price']].drop_duplicates())  # miro sus descripciones y precios reales

       stock_code              description  unit_price
26464     TEST001  This is a test product.        4.50
37434     TEST002  This is a test product.        1.00
230798   DCGSSBOY           BOYS PARTY BAG        3.36
230799  DCGSSGIRL          GIRLS PARTY BAG        3.36
554708   DCGSSBOY           BOYS PARTY BAG        3.29
554709  DCGSSGIRL          GIRLS PARTY BAG        3.29
740488   DCGSSBOY           BOYS PARTY BAG        1.25
740489  DCGSSGIRL          GIRLS PARTY BAG        1.25

**Hallazgo:** TEST001 y TEST002 tienen descripción literal "This is
a test product." — confirmado que son entradas de prueba del
sistema. DCGSSBOY y DCGSSGIRL son productos reales ("BOYS/GIRLS
PARTY BAG"), con 3 precios distintos a lo largo del tiempo —
patrón normal de un producto real, no administrativo.

**Decisión:** se agregan TEST001 y TEST002 a CODIGOS_NO_PRODUCTO.
DCGSSBOY y DCGSSGIRL no se tocan.

### 13.3 La compra de 80.995 unidades, ¿tiene su cancelación exacta todavía adentro?

In [74]:
cancelaciones_grandes = df[(df['quantity'] == -80995)]  # busco la cancelación de esa cantidad exacta
compras_grandes = df[(df['quantity'] == 80995) & (~df['invoice_no'].astype(str).str.startswith('C'))]  # y la compra original (no cancelación) de la misma cantidad
display(cancelaciones_grandes)
display(compras_grandes)

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
1065883,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom

**Hallazgo:** confirmado el caso sospechado en la revisión del PR —
la compra de 80.995 unidades (factura 581483, 09:15) tiene su
cancelación exacta 12 minutos después (factura C581484, 09:27),
mismo producto (23843) y mismo cliente (16446). Hoy el filtro solo
saca la cancelación, dejando la compra original en el dataset
limpio como si fuera una venta real que nunca se concretó.

**Decisión:** agregar a limpiar_datos() un paso que saque también
la compra original cuando existe una cancelación con mismo
customer_id, stock_code y cantidad exacta (en valor absoluto) —
pendiente de medir el alcance real antes de escribir el fix.

### 13.4 ¿Cuántos casos como este hay en todo el dataset?

In [75]:
cancelaciones = df[df['invoice_no'].astype(str).str.startswith('C')].copy()  # todas las filas de cancelación
cancelaciones['quantity_abs'] = cancelaciones['quantity'].abs()  # paso la cantidad a positivo para poder comparar

compras = df[~df['invoice_no'].astype(str).str.startswith('C')].copy()  # todas las filas que NO son cancelación

match = compras.merge(
    cancelaciones[['customer_id', 'stock_code', 'quantity_abs']],
    left_on=['customer_id', 'stock_code', 'quantity'],
    right_on=['customer_id', 'stock_code', 'quantity_abs']
)  # cruzo compras con cancelaciones que coincidan en cliente, producto y cantidad
print(len(match), "compras con cancelación exacta (mismo cliente, producto y cantidad)")
print(match['quantity'].describe())

53331 compras con cancelación exacta (mismo cliente, producto y cantidad)
count    53331.000000
mean        12.128106
std        487.907513
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max      80995.000000
Name: quantity, dtype: float64

**Hallazgo:** el cruce simple (mismo cliente, producto y cantidad,
sin mirar fecha) encuentra 53.331 coincidencias — pero la mediana de
cantidad es 1, sugiriendo que la mayoría son compras repetidas
normales, no la misma operación cancelada. Hay que verificar con la
fecha antes de confiar en este número.

### 13.5 Verificando con la fecha: ¿la cancelación es siempre después de la compra?

In [76]:
match_con_fechas = compras.merge(
    cancelaciones[['customer_id', 'stock_code', 'quantity_abs', 'invoice_date']],
    left_on=['customer_id', 'stock_code', 'quantity'],
    right_on=['customer_id', 'stock_code', 'quantity_abs'],
    suffixes=('_compra', '_cancelacion')
)  # mismo cruce de antes, pero esta vez trayendo también la fecha de cada lado
match_con_fechas['horas_hasta_cancelar'] = (
    match_con_fechas['invoice_date_cancelacion'] - match_con_fechas['invoice_date_compra']
).dt.total_seconds() / 3600  # diferencia en horas entre la compra y la "cancelación"

print(match_con_fechas['horas_hasta_cancelar'].describe())

count    53331.000000
mean       613.691226
std       5863.045038
min     -17568.666667
25%      -2688.816667
50%        225.883333
75%       4173.116667
max      17521.316667
Name: horas_hasta_cancelar, dtype: float64

**Hallazgo:** el mínimo es -17.568 horas (~732 días) y el percentil
25 completo es negativo — hay cancelaciones que aparecen ANTES que
la compra que supuestamente cancelan. Esto confirma que el cruce
sin fecha empareja coincidencias sin relación real, no la misma
operación. La mediana general es 225,9 horas (~9,5 días) — muy
lejos del caso confirmado (80.995 unidades, 12 minutos).

### 13.6 Filtrando por tiempo positivo — ¿hay un patrón real de cancelación rápida escondido en el ruido?

In [77]:
match_positivos = match_con_fechas[match_con_fechas['horas_hasta_cancelar'] > 0]  # me quedo solo con los casos donde la cancelación es DESPUÉS de la compra
print(len(match_positivos), "de", len(match_con_fechas), "tienen la cancelación después de la compra")
print(match_positivos['horas_hasta_cancelar'].describe())
print(match_positivos['horas_hasta_cancelar'].quantile([0.1, 0.25, 0.5, 0.75, 0.9]))

31154 de 53331 tienen la cancelación después de la compra
count    31154.000000
mean      4299.574559
std       3988.503269
min          0.016667
25%        790.487500
50%       3234.900000
75%       7032.445833
max      17521.316667
Name: horas_hasta_cancelar, dtype: float64
0.10      115.291667
0.25      790.487500
0.50     3234.900000
0.75     7032.445833
0.90    10032.430000
Name: horas_hasta_cancelar, dtype: float64

**Hallazgo:** incluso filtrando solo los casos donde la cancelación
es posterior, la mediana sigue siendo 3.234,9 horas (~135 días) y
el percentil 10 es 115 horas (~5 días) — lejos todavía del caso
confirmado de 12 minutos. Hay que mirar el extremo más bajo de la
distribución.

### 13.7 ¿Hay un grupo real de cancelaciones rápidas en el extremo más bajo?

In [78]:
print(match_positivos['horas_hasta_cancelar'].quantile([0.01, 0.02, 0.05]))  # miro bien al principio de la distribución
print((match_positivos['horas_hasta_cancelar'] < 1).sum(), "casos con cancelación dentro de la primera hora")
print((match_positivos['horas_hasta_cancelar'] < 24).sum(), "casos con cancelación dentro de las primeras 24 horas")
print((match_positivos['horas_hasta_cancelar'] < 24*7).sum(), "casos con cancelación dentro de la primera semana")

0.01    0.066667
0.02    0.166667
0.05    1.983333
Name: horas_hasta_cancelar, dtype: float64
1356 casos con cancelación dentro de la primera hora
1926 casos con cancelación dentro de las primeras 24 horas
3824 casos con cancelación dentro de la primera semana

**Hallazgo:** 1.356 casos se cancelan dentro de la primera hora,
1.926 dentro de las primeras 24 horas, 3.824 dentro de la primera
semana — números que sugieren un grupo real concentrado en tiempos
cortos, a confirmar con la densidad por hora en cada tramo.

### 13.8 Afinando el corte — ¿dónde exactamente baja la densidad a ritmo de fondo?

In [79]:
bins = [0, 1/6, 0.5, 1, 6, 24, 48, 168]  # cortes en horas: 10min, 30min, 1h, 6h, 24h, 48h, 1 semana
labels = ['<10min', '10-30min', '30min-1h', '1h-6h', '6h-24h', '24h-48h', '48h-1sem']
duracion_horas = [1/6, 1/3, 0.5, 5, 18, 24, 120]  # duración real de cada tramo, para calcular la tasa por hora

match_positivos['bucket'] = pd.cut(match_positivos['horas_hasta_cancelar'], bins=bins, labels=labels)  # clasifico cada caso en su tramo
conteo = match_positivos['bucket'].value_counts().reindex(labels)  # cuántos casos caen en cada tramo
tasa_por_hora = conteo / duracion_horas  # normalizo por duración, para comparar tramos de distinto largo

print(conteo)
print()
print("Casos por hora en cada ventana:")
print(tasa_por_hora.round(1))

bucket
<10min       633
10-30min     572
30min-1h     180
1h-6h        332
6h-24h       209
24h-48h      266
48h-1sem    1634
Name: count, dtype: int64

Casos por hora en cada ventana:
bucket
<10min      3798.0
10-30min    1716.0
30min-1h     360.0
1h-6h         66.4
6h-24h        11.6
24h-48h       11.1
48h-1sem      13.6
Name: count, dtype: float64

**Hallazgo:** la tasa de coincidencias por hora cae en cascada desde
<10 minutos (3.798/hora) hasta 1-6 horas (66,4/hora), y ahí se
aplana en un nivel de fondo parejo (11-14/hora) que se mantiene
igual hasta la semana — ese nivel parejo es ruido de coincidencias
sin relación real, no cancelaciones genuinas.

**Decisión:** se usa una ventana de 6 horas para identificar una
compra como "cancelada": mismo customer_id, stock_code y cantidad
(en valor absoluto), con la cancelación ocurriendo dentro de las 6
horas posteriores a la compra. Fuera de esa ventana, la coincidencia
se trata como casual, no se excluye.

### 13.9 Probando el fix antes de regenerar los datasets completos

In [80]:
import importlib
from src.data import clean
importlib.reload(clean)  # tomo la versión más nueva de clean.py, con el fix ya aplicado

import pandas as pd
prueba = pd.DataFrame({
    'invoice_no': ['1', '2'], 'stock_code': ['A', 'B'], 'description': ['x', 'y'],
    'quantity': [1, 2], 'invoice_date': pd.to_datetime(['2020-01-01', '2020-01-01']),
    'unit_price': [1.0, 2.0], 'customer_id': [1, 2], 'country': ['UK', 'UK']
})  # caso mínimo, solo para confirmar que no hay errores de sintaxis o lógica
resultado, log = clean.limpiar_datos(prueba)
display(log)
print("Sin errores")

                                  paso  filas  facturas
0                              inicial      2         2
1   sin compras con cancelación exacta      2         2
2                    sin cancelaciones      2         2
3                cantidad y precio > 0      2         2
4              sin códigos no-producto      1         1
5  sin duplicados (cantidades sumadas)      1         1
6                sin descripción vacía      1         1
7                      con customer_id      1         1

Sin errores

**Hallazgo:** el código corrió sin errores sobre un caso mínimo. La
fila con stock_code 'B' se excluyó por el filtro de códigos
no-producto (coincidencia del dato de prueba con un código real ya
excluido), confirmando que ese filtro sigue funcionando como
corresponde.

### 13.10 Regenerando los datasets con todos los fixes de la revisión del PR

In [81]:
df_rfm, log_rfm = clean.pipeline_completo('../data/raw/online_retail_II.xlsx', 
                                            '../data/processed/online_retail_rfm.parquet')
display(log_rfm)

                               paso   filas  facturas
                            inicial 1044848     53628
 sin compras con cancelación exacta 1043348     53404
                  sin cancelaciones 1024183     45112
              cantidad y precio > 0 1018154     39849
            sin códigos no-producto 1013721     39398
sin duplicados (cantidades sumadas)  991564     39398
              sin descripción vacía  991564     39398
                    con customer_id  764956     36490

                                  paso    filas  facturas
0                              inicial  1044848     53628
1   sin compras con cancelación exacta  1043348     53404
2                    sin cancelaciones  1024183     45112
3                cantidad y precio > 0  1018154     39849
4              sin códigos no-producto  1013721     39398
5  sin duplicados (cantidades sumadas)   991564     39398
6                sin descripción vacía   991564     39398
7                      con customer_id   764956     36490

In [ ]:
df_modelo, log_modelo = clean.pipeline_completo('../data/raw/online_retail_II.xlsx',
                                                   '../data/processed/online_retail_modelo.parquet',
                                                   conservar_sin_cliente=True)
display(log_modelo)

                               paso   filas  facturas
                            inicial 1044848     53628
 sin compras con cancelación exacta 1043348     53404
                  sin cancelaciones 1024183     45112
              cantidad y precio > 0 1018154     39849
            sin códigos no-producto 1013721     39398
sin duplicados (cantidades sumadas)  991564     39398
              sin descripción vacía  991564     39398

                                  paso    filas  facturas
0                              inicial  1044848     53628
1   sin compras con cancelación exacta  1043348     53404
2                    sin cancelaciones  1024183     45112
3                cantidad y precio > 0  1018154     39849
4              sin códigos no-producto  1013721     39398
5  sin duplicados (cantidades sumadas)   991564     39398
6                sin descripción vacía   991564     39398

**Hallazgo:** el paso nuevo "sin compras con cancelación exacta"
saca filas antes incluso de llegar a "sin cancelaciones" — y "sin
duplicados (cantidades sumadas)" ahora saca menos que antes del fix
del solapamiento de hojas (22.157 filas, contra 44.178 antes): buena
parte de lo que parecían duplicados reales dentro de una factura
eran en realidad copias entre las 2 hojas del Excel, sumadas dos
veces por error. Arreglar el solapamiento resolvió, de rebote, un
problema más grande de lo que parecía a simple vista.